services:
  - type: web
    name: steamlike-backend
    runtime: python
    plan: free
    buildCommand: sh build.sh
    startCommand: sh start.sh
    healthCheckPath: /api/health/
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.4"
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: DJANGO_SESSION_COOKIE_SECURE
        value: "True"
      - key: DJANGO_CSRF_COOKIE_SECURE
        value: "True"
      - key: MAILEROO_API_KEY
        sync: false
      - key: MAILEROO_FROM_ADDRESS
        value: "david@45f07c6711c75cfe.maileroo.org"
      - key: MAILEROO_FROM_NAME
        value: "Nexus Play"
      - key: MAILEROO_API_URL
        value: "https://smtp.maileroo.com/api/v2/emails"
      - key: MAILEROO_TIMEOUT
        value: "10"
      - key: DATABASE_URL
        fromDatabase:
          name: steamlike-db
          property: connectionString

databases:
  - name: steamlike-db
    databaseName: steamlike
    user: steamlike
    plan: free
